routes/web.php
<?php
/**
 * Copyright (c) 2019. JR Valencia (Developer).
 * Email: valencia_jr08@live.com
 * Redistribution and use in source and binary forms are permitted provided that the above copyright notice and this paragraph are duplicated in all such forms and that any documentation, advertising materials, and other materials related to such distribution and use acknowledge that the software was developed by me.
 *
 * I may not be used to endorse or promote products derived from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED "AS IN" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE .
 */


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::group(['middleware' => 'auth'], function() {

    //HOME
    Route::get('/', function(){
        return redirect('home');
    })->name('home');


    Route::get('home', 'HomeController@index')->name('home');

    //PROFILE

    Route::get('profile', 'UserController@profile')->name('profile');
    Route::put('profile', 'UserController@profileUpdate')->name('profile.update');


//  MANAGE USERS
    Route::group(['middleware' => ['permission:manage_users']], function () {

        Route::get('register', function(){
            return redirect('home');
        })->name('register');

        /*PERMISSIONS*/
        Route::resource('permissions', 'PermissionController', ['only' => [
            'index','destroy'
        ]]);

        /*ROLES*/
        Route::resource('roles', 'RoleController');

        /*USERS*/
        Route::resource('users', 'UserController');
        Route::any('users/users_data', 'UserController@usersDatatable')->name('users.dataTable');




    });

    //MANAGE INTRANET

    Route::group(['middleware' => ['permission:manage_content']], function () {


        /*CATEGORIES*/
        Route::resource('categories', 'CategoryController');

        /*POSTS*/
        Route::resource('posts', 'PostController');
        Route::any('posts_data', 'PostController@postDatatable')->name('post.dataTable');

    });


});

resources/views/layouts/sidebar/_nav-item.blade.php
<!-- Nav Item - Dashboard -->
<li class="nav-item {{ Request::segment(1) == 'home'  ? 'active' : ''}} {{Request::segment(1) == ''  ? 'active' : '' }}">
    <a class="nav-link" href="{{route('home')}}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
</li>

@can('manage_users')
<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->
<div class="sidebar-heading">
    USER MANAGEMENT
</div>

<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item {{ Request::segment(1) == 'permissions'  ? 'active' : ''}}">
    <a class="nav-link" href="{{route('permissions.index')}}">
        <i class="fas fa-user-shield"></i>
        <span>Permissions</span></a>
</li>
<li class="nav-item {{ Request::segment(1) == 'roles'  ? 'active' : ''}}">
    <a class="nav-link" href="{{route('roles.index')}}">
        <i class="fas fa-user-tag"></i>
        <span>Roles</span></a>
</li>
<li class="nav-item {{ Request::segment(1) == 'users'  ? 'active' : ''}}">
    <a class="nav-link" href="{{route('users.index')}}">
        <i class="fas fa-users"></i>
        <span>Users</span></a>
</li>
@endcan

@can('manage_content')

<!-- Divider -->
<hr class="sidebar-divider">

<!-- Heading -->
<div class="sidebar-heading">
    Intranet
</div>
<!-- Nav Item - Pages Collapse Menu -->
<li class="nav-item {{ Request::segment(1) == 'categories'  ? 'active' : ''}}">
    <a class="nav-link" href="{{route('categories.index')}}">
        <i class="fas fa-list"></i>
        <span>Manage Categories</span></a>
</li>

<li class="nav-item {{ Request::segment(1) == 'posts'  ? 'active' : ''}}">
    <a class="nav-link" href="{{route('posts.index')}}">
        <i class="far fa-clipboard"></i>
        <span>Posts</span></a>
</li>

@endcan

resources/views/layouts/sidebar/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav  sidebar sidebar-dark accordion " id="accordionSidebar" style="background-color:#880000">
    <br>
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{route('home')}}">
        {{--        <div class="sidebar-brand-icon rotate-n-15">--}}
        {{--            <i class="fas fa-laugh-wink"></i>--}}
        {{--        </div>--}}
        {{--        <div class="sidebar-brand-text mx-3">VMC Admin <sup>SAP PR-PO</sup></div>--}}

        <div class="mx-3">

            <img class="img-fluid " width="80" src="{{asset('images/logo/vcylogo.png')}}">

        </div>

    </a>
    <br>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

{{--NAVBAR-ITEMS--}}
@include('layouts.sidebar._nav-item')
{{--END NAVBAR ITEMS--}}
<!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->