routes/web.php
<?php
/**
 * Copyright (c) 2019. JR Valencia (Developer).
 * Email: valencia_jr08@live.com
 * Redistribution and use in source and binary forms are permitted provided that the above copyright notice and this paragraph are duplicated in all such forms and that any documentation, advertising materials, and other materials related to such distribution and use acknowledge that the software was developed by me.
 *
 * I may not be used to endorse or promote products derived from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED "AS IN" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE .
 */


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::group(['middleware' => 'auth'], function() {

    //HOME
    Route::get('/', function(){
        return redirect('home');
    })->name('home');


    Route::get('home', 'HomeController@index')->name('home');

    //PROFILE

    Route::get('profile', 'UserController@profile')->name('profile');
    Route::put('profile', 'UserController@profileUpdate')->name('profile.update');


//  MANAGE USERS
    Route::group(['middleware' => ['permission:manage_users']], function () {

        Route::get('register', function(){
            return redirect('home');
        })->name('register');

        /*PERMISSIONS*/
        Route::resource('permissions', 'PermissionController', ['only' => [
            'index','destroy'
        ]]);

        /*ROLES*/
        Route::resource('roles', 'RoleController');

        /*USERS*/
        Route::resource('users', 'UserController');
        Route::any('users/users_data', 'UserController@usersDatatable')->name('users.dataTable');




    });

    //MANAGE INTRANET

    Route::group(['middleware' => ['permission:manage_content']], function () {


        /*CATEGORIES*/
        Route::resource('categories', 'CategoryController');

        /*POSTS*/
        Route::resource('posts', 'PostController');
        Route::any('posts_data', 'PostController@postDatatable')->name('post.dataTable');

    });


});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model 
{

    protected $table = 'categories';
    public $timestamps = true;
    protected $fillable = array('category_name');

    public function post()
    {
        return $this->hasMany('App\Post');
    }

}

app/Http/Controllers/CategoryController.php
<?php
/**
 * Copyright (c) 2019. JR Valencia (Developer).
 * Email: valencia_jr08@live.com
 * Redistribution and use in source and binary forms are permitted provided that the above copyright notice and this paragraph are duplicated in all such forms and that any documentation, advertising materials, and other materials related to such distribution and use acknowledge that the software was developed by me.
 *
 * I may not be used to endorse or promote products derived from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED "AS IN" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE .
 */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Http\Requests\CategoryRequest;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::OrderBy('category_name','asc')->paginate(10);

        return view('pages.category.index')->with(compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $category = Category::create($request->all());

        session()->flash('message', 'Permission successfully created.');
        session()->flash('alert-class', 'alert-success');
        return redirect(route('categories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category::findOrFail($id);
        return view('pages.category.show')->with(compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return view('pages.category.edit')->with(compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        //find permission
        $category = Category::findOrFail($id);
        //update permission
        $category->update($request->all());

        //notify user
//        toastr()->success('Permission successfully updated', 'Updated', ["positionClass" => "toast-top-right",'progressBar'=>true]);
        session()->flash('message', 'Category successfully updated.');
        session()->flash('alert-class', 'alert-info');
        return redirect(route('categories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::findOrFail($id);
        $category->delete();

        session()->flash('message', 'Category successfully deleted.');
        session()->flash('alert-class', 'alert-danger');
        return redirect(route('categories.index'));
    }
}

resources/views/pages/category/_form.blade.php
@if(isset($category))

    {{ Form::model($category, ['route' => ['categories.update', $category->id], 'method' => 'put','id'=>'form','files'=>'true','class'=>'user']) }}
@else
    {{ Form::open(['route' => 'categories.store','id'=>'form','files'=>'true','class'=>'user']) }}
@endif
<div class="form-group row">
    <div class="col-sm-12 mb-3 mb-sm-0 {{ $errors->has('category_name') ? ' has-error' : '' }}">
        {{Form::text('category_name', old('category_name'),['class' => 'form-control form-control-user','id'=>'name','placeholder'=>'Category Name']) }}
        @if ($errors->has('category_name'))
            <span class="help-block" style="color: #a94442;">
                <strong>{{ $errors->first('category_name') }}</strong>
            </span>
        @endif
    </div>
</div>

@if(isset($category))
    <button type="submit" class="btn btn-primary btn-user btn-block">
        Update Category
    </button>
@else
    <button type="submit" class="btn btn-primary btn-user btn-block">
        Create Category
    </button>
@endif

<hr>

{{ Form::close() }}

resources/views/pages/category/_script.blade.php
<script>
    /*render delete modal*/
    $('#deleteModal').on('show.bs.modal', function (event) {

        var button = $(event.relatedTarget); // Button that triggered the modal
        var category_id = button.data('id');// Extract info from data-* attributes

        var modal = $(this);

        var url = '{{ route("categories.destroy", ":category_id") }}';
        url = url.replace(':category_id', category_id);

        modal.find('#delete-form').attr('action', url);
        modal.find('.modal-title').html('DELETE CATEGORY');
        modal.find('.modal-body').html('Are you sure you want to delete this category?');
    });
</script>

resources/views/pages/category/create.blade.php
@extends('layouts.app')
@section('title','Create-category')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Create Category</h1>
                    @if (session('message'))
                        <div class="alert {{session('alert-class')  }}">
                            {{ session('message') }}
                        </div>
                    @endif
                </div>
                @include('pages.category._form')
            </div>
        </div>
    </div>
@endsection

resources/views/pages/category/edit.blade.php
@extends('layouts.app')
@section('title','Edit-category')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Edit Category</h1>
                    @if (session('message'))
                        <div class="alert {{session('alert-class')  }}">
                            {{ session('message') }}
                        </div>
                    @endif
                </div>
                @include('pages.category._form')
            </div>
        </div>
    </div>
@endsection

resources/views/pages/category/index.blade.php
@extends('layouts.app')
@section('title','Categories')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Categories</h1>
                    @if (session('message'))
                        <div class="alert {{session('alert-class')  }}">
                            {{ session('message') }}
                        </div>
                    @endif
                </div>
                <div class="col-lg-12">
                    <div class="card shadow mb-4">
                                                <div class="card-header py-3">
                                                    <a href="{{route('categories.create')}}" class="btn btn-success btn-icon-split">
                                            <span class="icon text-white-50">
                                             <i class="fas fa-plus"></i>
                                            </span>
                                                        <span class="text">Create Category</span>
                                                    </a>
                                                </div>
                        <div class="table-responsive">
                            <table class="table table-striped"  width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Date Created</th>
                                    <th>Options</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse ($categories as $category)
                                    <tr>
                                        <td>{{$category->category_name}}</td>
                                        <td>{{\Carbon\Carbon::parse($category->created_at)->format('M d Y')}}</td>
                                        <td>
                                            <a href="{{route('categories.show',$category->id)}}" class="btn btn-success btn-circle">
                                                <i class="fas fa-eye"></i>
                                            </a>
                                            <a href="{{route('categories.edit',$category->id)}}" class="btn btn-info btn-circle">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a href="#" class="btn btn-danger btn-circle" data-id="{{$category->id}}"   data-toggle="modal" data-target="#deleteModal">
                                                <i class="fas fa-trash-alt"></i>
                                            </a>

                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="3">
                                            <p class="text-center">No Data</p>
                                        </td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>

                        {{ $categories->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page_js')
    @include('pages.category._script')
@endsection

resources/views/pages/category/show.blade.php
@extends('layouts.app')
@section('title','Category'.$category->category_name)
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Categories | {{$category->category_name}}</h1>
                </div>
                <div class="col-lg-12">
                    <div class="card shadow mb-4">
                                                <div class="card-header py-3">
                                                    <a href="{{route('categories.edit',$category->id)}}" class="btn btn-info btn-icon-split">
                                            <span class="icon text-white-50">
                                             <i class="fas fa-edit"></i>
                                            </span>
                                                        <span class="text">Edit Category</span>
                                                    </a>
                                                </div>
                        <div class="card-body">
                            <div class="form-group row ">
                                <div class="col-sm-3 mb-3 mb-sm-0">
                                    <h3>Category name:</h3>
                                </div>
                                <div class="col-sm-9 mb-3 mb-sm-0">
                                    <h3>{{$category->category_name}}</h3>
                                </div>
                            </div>

                            <div class="form-group row ">
                                <div class="col-sm-3 mb-3 mb-sm-0">
                                    <h3>Date created:</h3>
                                </div>
                                <div class="col-sm-9 mb-3 mb-sm-0">
                                    <h3>{{\Carbon\Carbon::parse($category->created_at)->format('M d Y')}}</h3>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection