routes/web.php
<?php
/**
 * Copyright (c) 2019. JR Valencia (Developer).
 * Email: valencia_jr08@live.com
 * Redistribution and use in source and binary forms are permitted provided that the above copyright notice and this paragraph are duplicated in all such forms and that any documentation, advertising materials, and other materials related to such distribution and use acknowledge that the software was developed by me.
 *
 * I may not be used to endorse or promote products derived from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED "AS IN" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE .
 */


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::group(['middleware' => 'auth'], function() {

    //HOME
    Route::get('/', function(){
        return redirect('home');
    })->name('home');


    Route::get('home', 'HomeController@index')->name('home');

    //PROFILE

    Route::get('profile', 'UserController@profile')->name('profile');
    Route::put('profile', 'UserController@profileUpdate')->name('profile.update');


//  MANAGE USERS
    Route::group(['middleware' => ['permission:manage_users']], function () {

        Route::get('register', function(){
            return redirect('home');
        })->name('register');

        /*PERMISSIONS*/
        Route::resource('permissions', 'PermissionController', ['only' => [
            'index','destroy'
        ]]);

        /*ROLES*/
        Route::resource('roles', 'RoleController');

        /*USERS*/
        Route::resource('users', 'UserController');
        Route::any('users/users_data', 'UserController@usersDatatable')->name('users.dataTable');




    });

    //MANAGE INTRANET

    Route::group(['middleware' => ['permission:manage_content']], function () {


        /*CATEGORIES*/
        Route::resource('categories', 'CategoryController');

        /*POSTS*/
        Route::resource('posts', 'PostController');
        Route::any('posts_data', 'PostController@postDatatable')->name('post.dataTable');

    });


});

app/Http/Controllers/PermissionController.php
<?php
/**
 * Copyright (c) 2019. JR Valencia (Developer).
 * Email: valencia_jr08@live.com
 * Redistribution and use in source and binary forms are permitted provided that the above copyright notice and this paragraph are duplicated in all such forms and that any documentation, advertising materials, and other materials related to such distribution and use acknowledge that the software was developed by me.
 *
 * I may not be used to endorse or promote products derived from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED "AS IN" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE .
 */

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\PermissionRequest;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\Gate;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::paginate(10);

        return view('pages.permission.index')->with(compact('permissions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.permission.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PermissionRequest $request)
    {
        $permission = Permission::create($request->all());

        session()->flash('message', 'Permission successfully created.');
        session()->flash('alert-class', 'alert-success');
        return redirect(route('permissions.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $permission = Permission::findOrFail($id);
        return view('pages.permission.show')->with(compact('permission'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permission = Permission::findOrFail($id);

        return view('pages.permission.edit')->with(compact('permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PermissionRequest $request, $id)
    {
        //find permission
        $permission = Permission::findOrFail($id);
        //update permission
        $permission->update($request->all());

        //notify user
//        toastr()->success('Permission successfully updated', 'Updated', ["positionClass" => "toast-top-right",'progressBar'=>true]);
        session()->flash('message', 'Permission successfully updated.');
        session()->flash('alert-class', 'alert-info');
        return redirect(route('permissions.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $permission = Permission::findOrFail($id);
        $permission->delete();

        session()->flash('message', 'Permission successfully deleted.');
        session()->flash('alert-class', 'alert-danger');
        return redirect(route('permissions.index'));
    }
}

resources/views/pages/permission/_form.blade.php
@if(isset($permission))

    {{ Form::model($permission, ['route' => ['permissions.update', $permission->id], 'method' => 'put','id'=>'form','files'=>'true','class'=>'user']) }}
@else
    {{ Form::open(['route' => 'permissions.store','id'=>'form','files'=>'true','class'=>'user']) }}
@endif
<div class="form-group row">
    <div class="col-sm-6 mb-3 mb-sm-0 {{ $errors->has('name') ? ' has-error' : '' }}">
        {{Form::text('name', old('name'),['class' => 'form-control form-control-user','id'=>'name','placeholder'=>'Permission Name']) }}
        @if ($errors->has('name'))
            <span class="help-block" style="color: #a94442;">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>
    <div class="col-sm-6 mb-3 mb-sm-0 {{ $errors->has('description') ? ' has-error' : '' }}">
        {{Form::text('description', old('description'),['class' => 'form-control form-control-user','id'=>'description','placeholder'=>'Description']) }}
        @if ($errors->has('description'))
            <span class="help-block" style="color: #a94442;">
                <strong>{{ $errors->first('description') }}</strong>
            </span>
        @endif
    </div>
</div>

@if(isset($permission))
    <button type="submit" class="btn btn-primary btn-user btn-block">
        Update Permission
    </button>
@else
    <button type="submit" class="btn btn-primary btn-user btn-block">
        Create Permission
    </button>
@endif

<hr>

{{ Form::close() }}

resources/views/pages/permission/_script.blade.php
<script>
    /*render delete modal*/
    $('#deleteModal').on('show.bs.modal', function (event) {

        var button = $(event.relatedTarget); // Button that triggered the modal
        var permission_id = button.data('id');// Extract info from data-* attributes

        var modal = $(this);

        var url = '{{ route("permissions.destroy", ":permission_id") }}';
        url = url.replace(':permission_id', permission_id);

        modal.find('#delete-form').attr('action', url);
        modal.find('.modal-title').html('DELETE PERMISSION');
        modal.find('.modal-body').html('Are you sure you want to delete this permission?');
    });
</script>

resources/views/pages/permission/create.blade.php
@extends('layouts.app')
@section('title','Create-permission')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Create Permission</h1>
                    @if (session('message'))
                        <div class="alert {{session('alert-class')  }}">
                            {{ session('message') }}
                        </div>
                    @endif
                </div>
                @include('pages.permission._form')
            </div>
        </div>
    </div>
@endsection

resources/views/pages/permission/edit.blade.php
@extends('layouts.app')
@section('title','Edit-permission')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Edit Permission</h1>
                    @if (session('message'))
                        <div class="alert {{session('alert-class')  }}">
                            {{ session('message') }}
                        </div>
                    @endif
                </div>
                @include('pages.permission._form')
            </div>
        </div>
    </div>
@endsection

resources/views/pages/permission/index.blade.php
@extends('layouts.app')
@section('title','Permission')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Permissions</h1>
                    @if (session('message'))
                        <div class="alert {{session('alert-class')  }}">
                            {{ session('message') }}
                        </div>
                    @endif
                </div>
                <div class="col-lg-12">
                    <div class="card shadow mb-4">
{{--                        <div class="card-header py-3">--}}
{{--                            <a href="{{route('permissions.create')}}" class="btn btn-success btn-icon-split">--}}
{{--                    <span class="icon text-white-50">--}}
{{--                     <i class="fas fa-plus"></i>--}}
{{--                    </span>--}}
{{--                                <span class="text">Create Permission</span>--}}
{{--                            </a>--}}
{{--                        </div>--}}
                        <div class="table-responsive">
                        <table class="table table-striped"  width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Date Created</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse ($permissions as $permission)
                                <tr>
                                    <td>{{$permission->name}}</td>
                                    <td>{{$permission->description}}</td>
                                    <td>{{\Carbon\Carbon::parse($permission->created_at)->format('M d Y')}}</td>
                                    <td>
{{--                                        <a href="{{route('permissions.show',$permission->id)}}" class="btn btn-success btn-circle">--}}
{{--                                            <i class="fas fa-eye"></i>--}}
{{--                                        </a>--}}
{{--                                        <a href="{{route('permissions.edit',$permission->id)}}" class="btn btn-info btn-circle">--}}
{{--                                            <i class="fas fa-edit"></i>--}}
{{--                                        </a>--}}
{{--                                        <a href="#" class="btn btn-danger btn-circle" data-id="{{$permission->id}}"   data-toggle="modal" data-target="#deleteModal">--}}
{{--                                            <i class="fas fa-trash-alt"></i>--}}
{{--                                        </a>--}}

                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="4">

                                    </td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                        </div>

                        {{ $permissions->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page_js')
    @include('pages.permission._script')
@endsection

resources/views/pages/permission/show.blade.php
@extends('layouts.app')
@section('title','Permission'.$permission->name)
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Permissions | {{$permission->name}}</h1>
                </div>
                <div class="col-lg-12">
                    <div class="card shadow mb-4">
{{--                        <div class="card-header py-3">--}}
{{--                            <a href="{{route('permissions.edit',$permission->id)}}" class="btn btn-info btn-icon-split">--}}
{{--                    <span class="icon text-white-50">--}}
{{--                     <i class="fas fa-edit"></i>--}}
{{--                    </span>--}}
{{--                                <span class="text">Edit Permission</span>--}}
{{--                            </a>--}}
{{--                        </div>--}}
                        <div class="card-body">
                            <div class="form-group row ">
                                <div class="col-sm-3 mb-3 mb-sm-0">
                                   <h3>Permission name:</h3>
                                </div>
                                <div class="col-sm-9 mb-3 mb-sm-0">
                                    <h3>{{$permission->name}}</h3>
                                </div>
                            </div>

                            <div class="form-group row ">
                                <div class="col-sm-3 mb-3 mb-sm-0">
                                    <h3>Date created:</h3>
                                </div>
                                <div class="col-sm-9 mb-3 mb-sm-0">
                                    <h3>{{\Carbon\Carbon::parse($permission->created_at)->format('M d Y')}}</h3>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection