routes/web.php
<?php
/**
 * Copyright (c) 2019. JR Valencia (Developer).
 * Email: valencia_jr08@live.com
 * Redistribution and use in source and binary forms are permitted provided that the above copyright notice and this paragraph are duplicated in all such forms and that any documentation, advertising materials, and other materials related to such distribution and use acknowledge that the software was developed by me.
 *
 * I may not be used to endorse or promote products derived from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED "AS IN" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE .
 */


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::group(['middleware' => 'auth'], function() {

    //HOME
    Route::get('/', function(){
        return redirect('home');
    })->name('home');


    Route::get('home', 'HomeController@index')->name('home');

    //PROFILE

    Route::get('profile', 'UserController@profile')->name('profile');
    Route::put('profile', 'UserController@profileUpdate')->name('profile.update');


//  MANAGE USERS
    Route::group(['middleware' => ['permission:manage_users']], function () {

        Route::get('register', function(){
            return redirect('home');
        })->name('register');

        /*PERMISSIONS*/
        Route::resource('permissions', 'PermissionController', ['only' => [
            'index','destroy'
        ]]);

        /*ROLES*/
        Route::resource('roles', 'RoleController');

        /*USERS*/
        Route::resource('users', 'UserController');
        Route::any('users/users_data', 'UserController@usersDatatable')->name('users.dataTable');




    });

    //MANAGE INTRANET

    Route::group(['middleware' => ['permission:manage_content']], function () {


        /*CATEGORIES*/
        Route::resource('categories', 'CategoryController');

        /*POSTS*/
        Route::resource('posts', 'PostController');
        Route::any('posts_data', 'PostController@postDatatable')->name('post.dataTable');

    });


});

app/Http/Controllers/RoleController.php
<?php
/**
 * Copyright (c) 2019. JR Valencia (Developer).
 * Email: valencia_jr08@live.com
 * Redistribution and use in source and binary forms are permitted provided that the above copyright notice and this paragraph are duplicated in all such forms and that any documentation, advertising materials, and other materials related to such distribution and use acknowledge that the software was developed by me.
 *
 * I may not be used to endorse or promote products derived from this software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED "AS IN" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE .
 */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\RoleRequest;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::paginate(10);

        return view('pages.role.index')->with(compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::get()->pluck('name', 'name');

        return view('pages.role.create')->with(compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RoleRequest $request)
    {
        $role = Role::create($request->except('permissions'));
        $permissions = $request->input('permissions') ? $request->input('permissions') : [];
        $role->givePermissionTo($permissions);

        session()->flash('message', 'Role successfully created.');
        session()->flash('alert-class', 'alert-success');
        return redirect(route('roles.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::findOrFail($id);
        return view('pages.role.show')->with(compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permissions = Permission::get()->pluck('name', 'name');

        $role = Role::findOrFail($id);

        if($role->name=='administrator'){
            abort(404);
        }

        return view('pages.role.edit')->with(compact('permissions','role'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::findOrFail($id);
        $role->update($request->except('permissions'));
        $permissions = $request->input('permissions') ? $request->input('permissions') : [];
        $role->syncPermissions($permissions);

        session()->flash('message', 'Role successfully updated.');
        session()->flash('alert-class', 'alert-info');
        return redirect(route('roles.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();

        session()->flash('message', 'Role successfully deleted.');
        session()->flash('alert-class', 'alert-danger');
        return redirect(route('roles.index'));
    }
}

resources/views/pages/role/_form.blade.php
@if(isset($role))

    {{ Form::model($role, ['route' => ['roles.update', $role->id], 'method' => 'put','id'=>'form','files'=>'true','class'=>'user']) }}
@else
    {{ Form::open(['route' => 'roles.store','id'=>'form','files'=>'true','class'=>'user']) }}
@endif
<div class="form-group row">
    <div class="col-sm-6 mb-3 mb-sm-0 {{ $errors->has('name') ? ' has-error' : '' }}">
        {{Form::text('name', old('name'),['class' => 'form-control form-control-user','id'=>'name','placeholder'=>'Role Name']) }}
        @if ($errors->has('name'))
            <span class="help-block" style="color: #a94442;">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>

    <div class="col-sm-6 mb-3 mb-sm-0 {{ $errors->has('description') ? ' has-error' : '' }}">
        {{Form::text('description', old('description'),['class' => 'form-control form-control-user','id'=>'description','placeholder'=>'Description']) }}
        @if ($errors->has('description'))
            <span class="help-block" style="color: #a94442;">
                <strong>{{ $errors->first('description') }}</strong>
            </span>
        @endif
    </div>
</div>

<div class="form-group row">
    <div class="col-sm-6 mb-3 mb-sm-0 {{ $errors->has('permissions') ? ' has-error' : '' }}">
        <label for="permissions" class="control-label" aria-describedby="permissions">Permissions</label>
        <small class="form-text text-muted">
            Hold "CTRL" key to select multiple permission
        </small>
        @if(isset($role))
            {!! Form::select('permissions[]', $permissions, old('permissions') ? old('permission') : $role->permissions()->pluck('name', 'name'), ['class' => 'form-control', 'multiple' => 'multiple','id'=>'select-permission',]) !!}
        @else
            {!! Form::select('permissions[]', $permissions, old('permissions'), ['class' => 'form-control', 'multiple' => 'multiple','id'=>'select-permission',]) !!}

        @endif

        @if ($errors->has('permissions'))
            <span class="help-block" style="color: #a94442;">
                <strong>{{ $errors->first('permissions') }}</strong>
             </span>
        @endif
    </div>
</div>

@if(isset($role))
    <button type="submit" class="btn btn-primary btn-user btn-block">
        Update Role
    </button>
@else
    <button type="submit" class="btn btn-primary btn-user btn-block">
        Create Role
    </button>
@endif

<hr>

{{ Form::close() }}

resources/views/pages/role/_script.blade.php
<script>
    /*render delete modal*/
    $('#deleteModal').on('show.bs.modal', function (event) {

        var button = $(event.relatedTarget); // Button that triggered the modal
        var role_id = button.data('id');// Extract info from data-* attributes

        var modal = $(this);

        var url = '{{ route("roles.destroy", ":role_id") }}';
        url = url.replace(':role_id', role_id);

        modal.find('#delete-form').attr('action', url);
        modal.find('.modal-title').html('DELETE ROLE');
        modal.find('.modal-body').html('Are you sure you want to delete this role?');
    });
</script>

resources/views/pages/role/create.blade.php
@extends('layouts.app')
@section('title','Create-roles')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Create Role</h1>
                    @if (session('message'))
                        <div class="alert {{session('alert-class')  }}">
                            {{ session('message') }}
                        </div>
                    @endif
                </div>
                @include('pages.role._form')
            </div>
        </div>
    </div>
@endsection

resources/views/pages/role/edit.blade.php
@extends('layouts.app')
@section('title','Edit-roles')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Edit Role</h1>
                    @if (session('message'))
                        <div class="alert {{session('alert-class')  }}">
                            {{ session('message') }}
                        </div>
                    @endif
                </div>
                @include('pages.role._form')
            </div>
        </div>
    </div>
@endsection

resources/views/pages/role/index.blade.php
@extends('layouts.app')
@section('title','Roles')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Roles</h1>
                    @if (session('message'))
                        <div class="alert {{session('alert-class')  }}">
                            {{ session('message') }}
                        </div>
                    @endif
                </div>
                <div class="col-lg-12">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <a href="{{route('roles.create')}}" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                     <i class="fas fa-plus"></i>
                    </span>
                                <span class="text">Create Roles</span>
                            </a>
                        </div>
                        <div class="table-responsive">
                        <table class="table table-striped" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Permissions</th>
                                <th>Date Created</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse ($roles as $role)
                                <tr>
                                    <td>{{$role->name}}</td>
                                    <td>{{$role->description}}</td>
                                    <td> @forelse ($role->permissions()->pluck('name') as $permission)
                                            <span class="badge badge-primary">{{ $permission }}</span>
                                        @empty
                                            <p>No Permission</p>
                                        @endforelse
                                    </td>
                                    <td>{{\Carbon\Carbon::parse($role->created_at)->format('M d Y')}}</td>
                                    <td>
                                        @if($role->name!='administrator')
                                        <a href="{{route('roles.show',$role->id)}}" class="btn btn-success btn-circle">
                                            <i class="fas fa-eye"></i>
                                        </a>

                                        <a href="{{route('roles.edit',$role->id)}}" class="btn btn-info btn-circle">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        <a href="#" class="btn btn-danger btn-circle" data-id="{{$role->id}}"   data-toggle="modal" data-target="#deleteModal">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                        @endif
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                <td colspan="5">
                                    <h4>No Data</h4>
                                </td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                        </div>

                        {{ $roles->links( "pagination::bootstrap-4") }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page_js')
    @include('pages.role._script')
@endsection

resources/views/pages/role/show.blade.php
@extends('layouts.app')
@section('title','Role-'.$role->name)
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="p-5">
                <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Roles | {{$role->name}}</h1>
                </div>
                <div class="col-lg-12">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <a href="{{route('roles.edit',$role->id)}}" class="btn btn-info btn-icon-split">
                    <span class="icon text-white-50">
                     <i class="fas fa-edit"></i>
                    </span>
                                <span class="text">Edit Role</span>
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="form-group row ">
                                <div class="col-sm-3 mb-3 mb-sm-0">
                                    <h3>Role name:</h3>
                                </div>
                                <div class="col-sm-9 mb-3 mb-sm-0">
                                    <h3>{{$role->name}}</h3>
                                </div>
                            </div>

                            <div class="form-group row ">
                                <div class="col-sm-3 mb-3 mb-sm-0">
                                    <h3>Description:</h3>
                                </div>
                                <div class="col-sm-9 mb-3 mb-sm-0">
                                    <h3>{{$role->description}}</h3>
                                </div>
                            </div>

                            <div class="form-group row ">
                                <div class="col-sm-3 mb-3 mb-sm-0">
                                    <h3>Date created:</h3>
                                </div>
                                <div class="col-sm-9 mb-3 mb-sm-0">
                                    <h3>{{\Carbon\Carbon::parse($role->created_at)->format('M d Y')}}</h3>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection